### ISSUE TITLE
Cas SSL certificate should be parameterizable

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumukit-login#30]
ideally, we should be able to simply set the certificate directly in the organization, though this is not a default option in omniauth-cas.

**Comment by flbulgarelli** [comment]
The problem with this is that `ca_path` looks to be defined in `Net:HTTP`. 

See:

* https://github.com/dlindahl/omniauth-cas/blob/8b9bc95220df1d6dd8f14e4514b3c3dbae0eac62/lib/omniauth/strategies/cas/service_ticket_validator.rb#L92
* https://ruby-doc.org/stdlib-2.4.1/libdoc/net/http/rdoc/Net/HTTP.html#attribute-i-ca_path

**Comment by flbulgarelli** [comment]
Perhaps we could dynamically and lazily create the directory in a temporal directory, and fill it with also temporal certificates

**Comment by flbulgarelli** [comment]
Or we could monkeypatch the library to accept `cert`and `key`, as described here: http://www.rubyinside.com/nethttp-cheat-sheet-2940.html. See _SSL/HTTPS request with PEM certificate
_
